"""empty message

Revision ID: ab2175f9e072
Revises: 2b681d169080
Create Date: 2025-01-22 12:50:51.697916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2175f9e072'
down_revision = '2b681d169080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('products', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # with op.batch_alter_table('products', schema=None) as batch_op:
    #     batch_op.drop_column('rating')

    # ### end Alembic commands ###
